import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistPixelSquare } from "geist/font/pixel";

import "./globals.css";
import { cn } from "@/lib/utils";
import MinecraftStars from "@/components/minecraft-stars";

export const metadata: Metadata = {
  title: "ama app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", GeistPixelSquare.className)}
    >
      <body className="min-h-full flex flex-col dark bg-[#090b1a] relative overflow-x-hidden">
        <MinecraftStars />
        {children}
      </body>
    </html>
  );
}
